# Generated by Django 6.0 on 2025-12-16 13:02

from django.db import migrations


def seed_data(apps, schema_editor):
    CompanyInfo = apps.get_model("core", "CompanyInfo")
    Department = apps.get_model("core", "Department")
    DepartmentHighlight = apps.get_model("core", "DepartmentHighlight")
    Artist = apps.get_model("core", "Artist")
    ArtistStat = apps.get_model("core", "ArtistStat")

    CompanyInfo.objects.get_or_create(
        name="Nyalo Intelligence",
        defaults={
            "tagline": "Technology, creativity, and security working together for modern teams.",
            "mission": "To integrate ICT support, security, engineering, and creativity into one reliable partner for modern businesses and artists.",
            "vision": "To be the go-to intelligence hub in Africa and beyond for secure technology, powerful software, and inspiring entertainment.",
            "owner_primary": "Munyaradzi Mutoo",
            "owner_secondary": "Emmanuel Vincent Chikarati",
            "email": "hello@nyalo.intel",
            "phone": "+000 000 0000",
            "location": "Global • Remote-first",
        },
    )

    departments = [
        (
            "ICT Support",
            "ict-support",
            "Helpdesk and ticketing for client issues, networking, and endpoint management to keep teams online.",
            [
                "24/7 ticketing desk for client incidents and requests",
                "Network setup, monitoring, and rapid troubleshooting",
                "Device onboarding, patching, and lifecycle management",
            ],
        ),
        (
            "Computer Hardware Repairs",
            "computer-hardware-repairs",
            "Diagnostics, upgrades, and component-level repairs for laptops, desktops, and peripherals.",
            [
                "Hardware diagnostics and rapid triage",
                "Upgrades for memory, storage, and GPUs",
                "Preventive maintenance and health checks",
            ],
        ),
        (
            "Software Engineering",
            "software-engineering",
            "Operating system customization and custom builds plus apps across web, desktop, and mobile.",
            [
                "Custom OS design, hardening, and feature extensions",
                "Website design and full-stack web apps",
                "Desktop, iOS, and Android app design and development",
                "API design, integrations, and cloud-native support",
            ],
        ),
        (
            "Cybersecurity",
            "cybersecurity",
            "Security services and tooling sales, protection programs, and safety operations for clients.",
            [
                "Security assessments, hardening, and safety roadmaps",
                "Sales and deployment of vetted security solutions",
                "Incident response playbooks, monitoring, and training",
            ],
        ),
        (
            "Music and Entertainment",
            "music-and-entertainment",
            "Artist sponsorships, bios, and movement tracking with full social presence and booking.",
            [
                "Artist bios with YouTube, Facebook, TikTok, and Instagram links",
                "Metrics for streams, shows, releases, and social growth",
                "Studio recording, audio engineering, and live sound",
                "Bookings for shows, photo shoots, and video shoots",
            ],
        ),
        (
            "Graphic Design",
            "graphic-design",
            "Creative direction, branding, and all graphic assets with booking for visual deliverables.",
            [
                "Brand identities, campaigns, and production-ready assets",
                "Print, digital, and social graphics with motion options",
                "Booking system for design sprints and asset drops",
            ],
        ),
        (
            "Merchandise Sales",
            "merchandise-sales",
            "Clothing and jewelry sales tightly aligned with the brand and graphic design output.",
            [
                "Custom apparel and jewelry design with the graphics team",
                "Online store setup, inventory, and fulfillment support",
                "Pop-up retail, promo bundles, and artist-linked drops",
            ],
        ),
    ]

    for order, (name, slug, summary, highlights) in enumerate(departments):
        dept, _ = Department.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "summary": summary,
                "order": order,
            },
        )
        if not dept.highlights.exists():
            for h_order, text in enumerate(highlights):
                DepartmentHighlight.objects.create(
                    department=dept, text=text, order=h_order
                )

    artists = [
        {
            "name": "JB Supervisor",
            "role": "Artist · Nyalo Intelligence sponsored",
            "bio": "Afro-fusion and contemporary sounds backed by Nyalo Intelligence studio and production teams.",
            "youtube_url": "https://youtu.be/87OaS_ys004?si=9TvsNgjxI2ca2FzQ",
            "stats": [
                "New release available on YouTube",
                "Bookings available for shows and studio sessions",
            ],
        },
    ]

    for order, artist in enumerate(artists):
        art, _ = Artist.objects.get_or_create(
            name=artist["name"],
            defaults={
                "role": artist.get("role", ""),
                "bio": artist.get("bio", ""),
                "youtube_url": artist.get("youtube_url", ""),
                "facebook_url": artist.get("facebook_url", ""),
                "tiktok_url": artist.get("tiktok_url", ""),
                "instagram_url": artist.get("instagram_url", ""),
                "order": order,
            },
        )
        if not art.stats.exists():
            for s_order, text in enumerate(artist.get("stats", [])):
                ArtistStat.objects.create(artist=art, text=text, order=s_order)


def unseed_data(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    CompanyInfo = apps.get_model("core", "CompanyInfo")
    Artist = apps.get_model("core", "Artist")

    Department.objects.filter(
        slug__in=[
            "ict-support",
            "computer-hardware-repairs",
            "software-engineering",
            "cybersecurity",
            "music-and-entertainment",
            "graphic-design",
            "merchandise-sales",
        ]
    ).delete()
    Artist.objects.filter(name__in=["JB Supervisor"]).delete()
    CompanyInfo.objects.filter(name="Nyalo Intelligence").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
