# Generated by Django 6.0 on 2025-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='owner_primary',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='owner_secondary',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
