# Generated by Django 6.0 on 2025-12-16 13:13

from django.db import migrations


def update_contact(apps, schema_editor):
    CompanyInfo = apps.get_model("core", "CompanyInfo")
    CompanyInfo.objects.update_or_create(
        name="Nyalo Intelligence",
        defaults={
            "email": "mutoomunya@gmail.com · chikaratiemmanuel@gmail.com",
            "phone": "+263788104537 / +263777707882",
        },
    )


def reverse_update_contact(apps, schema_editor):
    CompanyInfo = apps.get_model("core", "CompanyInfo")
    CompanyInfo.objects.filter(name="Nyalo Intelligence").update(
        email="hello@nyalo.intel",
        phone="+000 000 0000",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companyinfo_mission_companyinfo_owner_primary_and_more"),
    ]

    operations = [
        migrations.RunPython(update_contact, reverse_update_contact),
    ]
