# Generated by Django 6.0 on 2025-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='theme_accent',
            field=models.CharField(default='#38bdf8', help_text='Accent HEX color for this department', max_length=7),
        ),
        migrations.AddField(
            model_name='department',
            name='theme_primary',
            field=models.CharField(default='#0ea5e9', help_text='Primary HEX color for this department', max_length=7),
        ),
    ]
