# Generated by Django 6.0 on 2025-12-16 14:22

from django.db import migrations


def seed_themes(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    themes = {
        "ict-support": ("#22c55e", "#4ade80"),
        "computer-hardware-repairs": ("#f97316", "#fdba74"),
        "software-engineering": ("#6366f1", "#a5b4fc"),
        "cybersecurity": ("#f43f5e", "#fb7185"),
        "music-and-entertainment": ("#ec4899", "#f9a8d4"),
        "graphic-design": ("#14b8a6", "#5eead4"),
        "merchandise-sales": ("#eab308", "#fde047"),
    }
    for slug, (primary, accent) in themes.items():
        Department.objects.filter(slug=slug).update(
            theme_primary=primary, theme_accent=accent
        )


def unseed_themes(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    Department.objects.all().update(theme_primary="#0ea5e9", theme_accent="#38bdf8")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_department_theme_accent_department_theme_primary"),
    ]

    operations = [
        migrations.RunPython(seed_themes, unseed_themes),
    ]
